[tool.poetry]
name = "demucs-redux"
version = "0.0.1"
description = "Inference-only port of demucs"
authors = ["Alexandre Défossez <defossez@fb.com>", "Dávid Szakállas <david.szakallas@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [
    { include = "demucs" }
]

[tool.poetry.dependencies]
python = ">=3.9"
torch = "^2.2.0"
openunmix = "^1.2.1"
julius = "^0.2.7"

[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
mypy = "^1.8.0"
pylint = "^3.0.3"
black = { version = "^23.12.1" }
importmagic = "^0.1.7"
pre-commit = "^3.6.0"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.mypy]
packages = 'demucs'
# strict = True

[tool.poetry.scripts]
ptexport = 'demucs.cmd.ptexport:main'
